### PR TITLE
Handle self.assertRaises being used as context manager.

### PR DESCRIPTION
**Pull request by EnTeQuAk**

### CODE REVIEW

**Comment by The-Compiler** [comment]
And here we meet again :wink:

Seems like this broke the tests according to Travis - I also guess a [added test](https://github.com/pytest-dev/unittest2pytest/blob/develop/tests/fixtures/self_assert/assertRaises_in.py) for this scenario would be welcome.

(PS: https://www.webshox.org/ has a redirect loop, I guess that's unintended?)

**Comment by EnTeQuAk** [comment]
Hey! :smiley: Yeah, I'll add some test and will run the other tests, I kinda just ran it against a bigger project and found that sufficient for now. Stay tuned.

**Comment by htgoebel** [comment]
The fixes for context-handlers should better go into a fixer of its own, matching on `with ...`. This is much more reliable then testing for `unittest.case._sentinel`. And it could easily be used for the other context-handlers which test e.g. the exception message (see https://pytest.org/latest/assert.html#assertions-about-expected-exceptions)

**Comment by EnTeQuAk** [comment]
Sounds good to me @htgoebel, especially for python3 the `_sentinel` check doesn't work so I will change that.

**Comment by RonnyPfannschmidt** [comment]
@adamchainz how did you en-cooperate the changes of this one (at second glance it seems like i should have merged this one first for correct attribution)

**Comment by adamchainz** [comment]
I took half of it, I didn't find the `_sentinel` was defined when I looked on Python 2 or 3 so I had to rewrite with `None`. Also the whitespace changes weren't required.

**Comment by RonnyPfannschmidt** [comment]
ok, i believe its fine as is

@EnTeQuAk ping me in case you disagree

**Comment by adamchainz** [comment]
I'm happy to rebase and create a branch that adds @EnTeQuAk as a
contributor by unmerging part of my commit and merging his

On 25 May 2016 at 13:43, Ronny Pfannschmidt <notifications@github.com>
wrote:

> ok, i believe its fine as is
>
> @EnTeQuAk <https://github.com/EnTeQuAk> ping me in case you disagree
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/pytest-dev/unittest2pytest/pull/2#issuecomment-221563747>
>



-- 
Adam

**Comment by RonnyPfannschmidt** [comment]
in case he asks for it, i'd appreciate if you follow up with that

thanks for the work

**Pull request closed without merging**
