### PR TITLE
Allow non-string keys when rewriting assertDictContainsSubset

### LINKED ISSUE #54: dict(\2, **\1) requires all dictionary keys to be strings
As https://www.python.org/dev/peps/pep-0584/#dict-d1-d2 points out, 

> [`dict(d1, **d2)`] only works when d2 is entirely string-keyed
>
>```python
>>>> d1 = {"spam": 1}
>>>> d2 = {3665: 2}
>>>> dict(d1, **d2)
>Traceback (most recent call last):
>  ...
>TypeError: keywords must be strings
>```

So, when rewriting `self.assertDictContainsSubset(a, b)` as `assert dict(b, **a) == b`, we're introducing a test error if the dict can contain non-string keys.

### PR DESCRIPTION
**Pull request by verhovsky**
and also update supported Python versions in tox.ini.

#54

### CODE REVIEW

**Comment by verhovsky** [comment]
I guess `{**a, **b}` is not supported syntax. One tricky thing is that `dict(a, **b)` actually works in Python 2. We will have to either drop Python 2 support or have a flag like `--py2` (and `--py3`?) to enable that. While we're doing this, we might as well add a `--py39` because on 3.9 you can do `a | a == a`.

**Comment by nicoddemus** [comment]
Thanks @verhovsky! 

My 2 cents:

I think dropping Python 2 is fine, and then we always use the Python 3 syntax (`{**a, **b}`).

If not, not sure we need a flag, we might just use the version of the Python we are running (`sys.version_info`).

**Comment by verhovsky** [comment]
> use the version of the Python we are running

If someone doesn't realize their `pip` command is Python 2 pip and does `pip install unittest2pytest`, they will run into this bug when they run `unittest2pytest <whatever>`. In a way dropping Python 2 support has the same effect, since installing unittest2pytest under Python 2 will install the last version, which is the one that rewrites it as `dict(b, **a)`.

**Comment by nicoddemus** [comment]
LGTM!

This also warrants a changelog entry. 👍

**Review by nicoddemus — APPROVED** [review]

**Review by nicoddemus — APPROVED** [review]
Great work!

**Comment by nicoddemus** [comment]
Created follow up in #73.

Sorry @verhovsky for the long delay here.

**Pull request closed without merging**
